delpoy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  github_url: prosemirror.xheldon.com
language: node_js
node_js:
  - "10"
install:
  - "yarn install"
  - "bin/pm install"
before_script:
  - "cd website"
  - "make"
script:
cache:
  directories:
    - "node_modules"
env:
    - NODE_ENV=prod
after_success:
    - cd docs
    - git init
    - git checkout -b gh-pages
    - git add .
    - git -c user.name='travis' -c user.email='travis' commit -m 'update docs'
    - git push -f -q https://Xheldon:$GITHUB_TOKEN@github.com/Xheldon/prosemirror-doc-cn gh-pages